config/routes.rb
Rails.application.routes.draw do
  # get 'rangers/new'

  root 'home#index'
  resources :parks
  resources :rangers


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  has_and_belongs_to_many :rangers
end

app/models/parks_rangers.rb
class ParksRangers < ApplicationRecord
  belongs_to :park
  belongs_to :ranger
end

app/models/ranger.rb
class Ranger < ApplicationRecord
  has_and_belongs_to_many :parks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    before_action :set_park, only: [:show, :edit, :update, :destroy]

  def index
    @parks = Park.order(:name)
    @rangers = Ranger.all

  end

  def show
    @rangers = Ranger.all

  end

  def new
    @park = Park.new
    @rangers = Ranger.all
  end

  def edit
    @rangers = Ranger.all
  end

  # POST /parks
  def create
    # new park is assigned to current_user
    @park = Park.new(park_params)

    upload_file
    if @park.save
      delete_old_file
      redirect_to @park, notice: 'Park was successfully created.'
    else
      render :new
    end
  end


  def update
    upload_file
    if @park.update(park_params)
      delete_old_file
      redirect_to @park, notice: 'Park was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    delete_old_file @park.picture
    @park.destroy
    redirect_to parks_url, notice: 'Park was successfully destroyed.'
  end

  private
    def set_park
      @park = Park.find(params[:id])
    end

    # def park_params
    #   params.require(:park).permit(:name, :description, :picture)
    # end

    def park_params
      params.require(:park).permit(:name, :description,:picture, :ranger_ids => [])
    end

    def upload_file
      if params[:park][:picture].present?
        if @park.valid?
          uploaded_file = params[:park][:picture].path
          cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)
          @old_file = @park.picture
          @park.picture = cloudnary_file['public_id']
        end
        params[:park].delete :picture
      end
    end

  def delete_old_file old_file = nil
    file_to_del = old_file || @old_file
    Cloudinary::Uploader.destroy(file_to_del, :invalidate => true) unless file_to_del.blank?
  end

end

app/controllers/rangers_controller.rb
class RangersController < ApplicationController
  before_action :set_ranger, only: [:show, :edit, :update, :destroy]

  def index
    @rangers = Ranger.all
    p @rangers
    # Product.joins(:category).merge(Category.order(priority: :desc))
    @parks = Park.all
  end

  def show
    @parks = Park.all

  end

  def new
    @ranger = Ranger.new
    @parks = Park.all
  end

  def edit
    @parks = Park.all
  end

  def create
    @ranger = Ranger.new(ranger_params)

    if @ranger.save
      redirect_to rangers_path, notice: 'Ranger was successfully created.'
    else
      render :new
    end
  end

  def update
    if @ranger.update(ranger_params)
      redirect_to @ranger, notice: 'Ranger was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ranger.destroy
    redirect_to rangers_path, notice: 'Ranger was successfully destroyed.'
  end


  private
    def set_ranger
      @ranger = Ranger.find(params[:id])
    end

    def ranger_params
      params.require(:ranger).permit(:name, :park_ids => [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/rangers_helper.rb
module RangersHelper
end

app/views/home/index.html.erb
  <%= image_tag 'parks.jpg', class: 'full-width' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Parks &amp; Rec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Parks &amp; Rec</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/parks">All Parks</a></li>
            <li><a href="/rangers">All Rangers</a></li>

          
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Sharan</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  <br><br><br>

  <div class="container">
    <div id="notice">
      <% flash.each do |key, value| %>
        <div class="alert alert-info" role="alert">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </div>

  </body>
</html>

app/views/parks/_form.html.erb
<%= bootstrap_form_for(@park) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.collection_check_boxes :ranger_ids, @rangers, :id, :name %>
  <%= f.file_field :picture %>
  <%= f.submit "Submit" %>
<% end %>

app/views/parks/edit.html.erb
<div class="form-container">
  <h1>Editing Park</h1>
    <%= render 'form', park: @park %>

    <h4> current photo: </h4>
      <img src="http://res.cloudinary.com/dcia1leyj/image/upload/c_fill,h_200,w_200/<%= @park.picture %>">

    <br><br>

    <button type="button" class="btn btn-lg btn-default">
      <%= link_to 'Show', @park %>
    </button>

    <button type="button" class="btn btn-lg btn-default">
      <%= link_to 'Back', parks_path %>
    </button>
    
</div>

app/views/parks/index.html.erb
<h1>America's Best National Parks</h1>
<button class="btn btn-lg btn-default">
  <%= link_to 'Create New Park', new_park_path %>
</button>

<table class="table col-md-12">
  <thead>
    <tr>
      <th class="col-md-4"><h4>Park</h4></th>
      <th class="col-md-5"><h4>Description</h4></th>
      <th class="col-md-2"><h4>Actions</h4></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td>
          <img src="http://res.cloudinary.com/dcia1leyj/image/upload/c_fill,h_200,w_400/<%= park.picture %>">
        </td>
        <td>
          <strong><%= park.name %></strong><br>
          <p><%= park.description %></p>
          <% if park.rangers.length > 0 %>
            Rangers
            <% park.rangers.each do |ranger | %>
            <li>  <%= ranger.name %></li>
            <% end %>
          <% else %>
          There is no assigned ranger.
          <% end %>


        </td>
        <td>
          <button type="button" class="btn btn-lg btn-block btn-default"><%= link_to 'Show', park %></button><br>
          <button type="button" class="btn btn-lg btn-block btn-default"><%= link_to 'Edit', edit_park_path(park) %></button><br>
          <button  type="button" class="btn btn-lg btn-block btn-default"><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parks/new.html.erb
<div class="form-container">
  <h1>Create New Park</h1>

  <%= render 'form', park: @park %>

  <br><br>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to All Parks', parks_path %></button>

</div>

app/views/parks/show.html.erb
<div class="kill-panel">
  <div class="panel panel-default panel-transparent">

    <div class="panel-heading">
      <h2 class="panel-title"><%= @park.name %></h2>
    </div>

    <div class="panel-body">
      <%= @park.description %><br><br>

      <% if @park.rangers.length > 0 %>
      Rangers
        <% @park.rangers.each do |ranger | %>
          <li><%= ranger.name %></li>
        <% end %>
      <% else %>
      There is no assigned ranger.
      <% end %>


      <p>
        <%= cl_image_tag(@park.picture, :width => 400, :height => 200, :crop => :fill) %>
      </p>
    </div>
  </div>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Edit', edit_park_path(@park) %></button>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to All Parks', parks_path %></button><br>

</div>

app/views/rangers/edit.html.erb
<div class="form-container">
  <h1>Edit Ranger</h1>

  <%= bootstrap_form_for(@ranger) do |f| %>
    <%= f.text_field :name %>
    <%= f.collection_check_boxes :park_ids, @parks, :id, :name %>
    <%= f.submit "Submit" %>
  <% end %>


  <br><br>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to Rangers', rangers_path %></button>

</div>

app/views/rangers/index.html.erb
<h1>America's Best National Park Rangers</h1>
<button class="btn btn-lg btn-default">
  <%= link_to 'Create New Ranger', new_ranger_path %>
</button>

<table class="table col-md-12">
  <thead>
    <tr>
      <th class="col-md-3"><h4>Ranger</h4></th>
      <th class="col-md-2"><h4>Parks</h4></th>
      <th class="col-md-1"><h4>Parks No</h4></th>
      <th class="col-md-2"><h4></h4></th>
      <th class="col-md-2"><h4></h4></th>
      <th class="col-md-2"><h4></h4></th>
    </tr>
  </thead>

  <tbody>
    <% @rangers.each do |ranger| %>
      <tr>

        <td>
          <strong><%= ranger.name %></strong><br>
        </td>


        <td>
          <% if ranger.parks.length > 0 %>
          <ul style="list-style-type:none; padding-left:0">
            <% ranger.parks.each do |park| %>
              <li><%= park.name %></li>
            <% end %>
          </ul>
          <% else %>
          <h5>UNEMPLOYED. USELESS.<h5>
          <% end %>
        </td>

        <td>

            <p><%= ranger.parks.length %></p>

          </td>

        <td>
          <button type="button" class="btn btn-block btn-default"><%= link_to 'Profile', ranger %></button>
        </td>

        <td>
          <button type="button" class="btn btn-block btn-default"><%= link_to 'Edit', edit_ranger_path(ranger) %></button>
        </td>
        <td>
          <button  type="button" class="btn btn-block btn-default"><%= link_to 'Destroy', ranger, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rangers/new.html.erb
<div class="form-container">
  <h1>Create New Ranger</h1>

  <%= bootstrap_form_for(@ranger) do |f| %>
    <%= f.text_field :name %>
    <%= f.collection_check_boxes :park_ids, @parks, :id, :name %>
    <%= f.submit "Submit" %>
  <% end %>


  <br><br>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to Rangers', rangers_path %></button>

</div>

app/views/rangers/show.html.erb
<div class="kill-panel">
  <div class="panel panel-default panel-transparent">

    <div class="panel-heading">
      <h2 class="panel-title"><%= @ranger.name %></h2>
    </div>

    <div class="panel-body">

      <% if @ranger.parks.length > 0 %>
      <ul>
        <% @ranger.parks.each do |ranger | %>
        <li>  <%= ranger.name %> </li>
        <% end %>
      </ul>
      <% else %>
      There is no assigned ranger.
      <% end %>



    </div>
  </div>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Edit', edit_ranger_path(@ranger) %></button>

  <button type="button" class="btn btn-lg btn-default"><%= link_to 'Back to All Rangers', rangers_path %></button><br>

</div>